name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
        name:
          description: 'Person to greet'
          default: 'World'
          required: true
          type: string

env:
  prj_name: itvdn-demo

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Send greeting
          run: echo "Hello ${{ inputs.name }}"
        - uses: actions/checkout@v3
        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 6.0.x
        - name: Restore dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build --no-restore
        - name: Test
          run: dotnet test --no-build --verbosity normal

        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v3.1.2
          with:
            path: ${{ github.workspace }}/${{ env.prj_name }}/bin/Debug/net6.0/${{ env.prj_name }}.dll

